mealplans/urls.py
from django.urls import path

from mealplans.views import (
    MealPlanListView,
    CreateMealPlan,
    MealPlanDetailView,
    UpdateMealPlan,
    DeleteMealPlan
)

urlpatterns = [
    path("meal_plans/", MealPlanListView.as_view(), name="meal_plans"),
    path("meal_plans/new/", CreateMealPlan.as_view(), name="mealplan_new"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="mealplan_detail"),
    path("<int:pk>/edit/", UpdateMealPlan.as_view(), name="mealplan_edit"),
    path("<int:pk>/delete/", DeleteMealPlan.as_view(), name="mealplan_delete"),

]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("mealplans/", include("mealplans.urls")),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

mealplans/models.py
from pickle import TRUE
from django.db import models
from django.conf import settings
from recipes.models import Recipe

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField(null=TRUE)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="meal_plans",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField(
        "recipes.Recipe", related_name="meal_plans"
    )

mealplans/views.py
from django.shortcuts import render

from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from mealplans.models import MealPlan


class MealPlanListView(ListView):
    model = MealPlan
    template_name = "mealplans/list.html"
    paginate_by = 10

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class CreateMealPlan(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "mealplans/new.html"
    fields = ["name", "recipes", "date"]

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("mealplan_detail", pk=plan.id)


class MealPlanDetailView(DetailView):
    model = MealPlan
    template_name = "mealplans/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class UpdateMealPlan(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "mealplans/edit.html"
    fields = ["name", "recipes", "date"]
    success_url = reverse_lazy("meal_plans")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    # def get_success_url(self) -> str:
    #     return reverse_lazy("meal_plans", args=[self.object.id])


class DeleteMealPlan(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "mealplans/delete.html"
    success_url = reverse_lazy("meal_plans")

    # def get_queryset(self):
    #     return DeleteMealPlan.objects.filter(owner=self.request.user)

mealplans/templates/mealplans/delete.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ mealplan.name }}"?</p>
    {{ form.as_p }}
    <div class="control">
      <button class="button">Delete</button>
    </div>
  </form>
</main>
{% endblock content %}

mealplans/templates/mealplans/detail.html
{% extends 'base.html' %}

{% load static %}
{% load markdownify %}

{% block content %}
<main class="recipe-detail">
  <div>
    <a href="{% url 'mealplan_edit' mealplan.id %}">Edit</a>
    <a href="{% url 'mealplan_delete' mealplan.id %}">Delete</a>
  </div>
  <div>
    <h2>Recipes for {{ mealplan.name }} on {{mealplan.date}}</h2>
    {% for recipe in mealplan.recipes.all %}
    <p><a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a></p>
    {% endfor %}
  </div>
</main>

{% endblock content %}

mealplans/templates/mealplans/edit.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

mealplans/templates/mealplans/list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div>
  <a href="{% url 'mealplan_new' %}">Create</a>
</div>

<main class="recipe-grid">
  {% for meal_plan in mealplan_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'mealplan_detail' meal_plan.pk %}">{{ meal_plan.name }}</a>
    </h2>
    {% for recipe in meal_plan.recipes.all %}
    <p><a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a></p>
    {% endfor %}

  </div>
  {% endfor %}
</main>
{% endblock content %}



{% block pagination %}
<div class="footer">
  <span>
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; First</a>
    <a href="?page={{ page_obj.previous_page_number}}">Previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"> Next </a>
    <a href="?page={{ page_obj.paginator.num_pages }}"> Last&raquo; </a>
    {% endif %}
  </span>
</div>
{% endblock pagination %}

mealplans/templates/mealplans/new.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<main class="recipe-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>

{% endblock content %}